[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=/home/mguillen/.config/qt6ct/colors/avalon-amber.conf
standard_dialogs=default
icon_theme=Adwaita

[Fonts]
fixed="3270 Nerd Font Mono,14,-1,5,50,0,0,0,0,0"
general="3270 Nerd Font Propo,14,-1,5,50,0,0,0,0,0"
